apiVersion: skaffold/v4beta6
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: shahab5191/shinchat-auth
    context: ./auth-srv
    docker:
      dockerfile: Dockerfile
      target: dev
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: shahab5191/shinchat-chat
    context: ./chat-srv
    docker:
      dockerfile: Dockerfile
      target: dev
    sync:
      manual:
        - dest: .
          src: '/src/**/*.ts'
