apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: shahab5191/shinchat-chat:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: POSTGRES_PASSWORD
        - name: URL_PREFIX
          value: "/api/v1"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  selector:
    app: chat
  ports:
  - name: chat
    protocol: TCP
    port: 4001
    targetPort: 4001
