apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: shahab5191/shinchat-auth:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: URL_PREFIX
          value: "/api/v1"
        - name: POSTGRES_ADDRESS
          valueFrom:
            secretKeyRef:
              name: postgres-address
              key: POSTGRES_ADDRESS
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-url
              key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 4000
    targetPort: 4000
